### ISSUE TITLE
Put project environment versions in the Version Catalog 

### ISSUE THREAD

**Issue by majid-khosravi** [moallemi/Film-Time#47]
According to have lots of different modules in this project and that these modules should use the same version parameter, we are able to set some of them values as project environment version variable  in **libs.version.toml** file and use the same version.
This improvement helps us to keep modules easy maintainable later.

**My sugestion includes these values:**
1. compileSdk
2. minSdk
3. kotlinCompilerExtensionVersion

**Comment by moallemi** [comment]
hey @majid-khosravi.

Thanks for your suggestion 🙏👌
The reason why we have this build.gradle.kts junk is that I am planning to create `build-logic` module and remove all duplicate gradle configuration in all modules. In that case we only have one place to configure compile SDK and minSDK and etc. 
I do not want you to spent time on something that will change in following weeks. But I am always open for contributions and for now it's up to you to move these configs to libs.version.toml since we migrate to `build-logic` module very soon.
